import coffee from "../assets/CategoryImage/coffee.png";
import all from "../assets/CategoryImage/all.png";
import juice from "../assets/CategoryImage/juice.png";
import dessert from "../assets/CategoryImage/dessert.png";
import burger from "../assets/CategoryImage/burger.png";

export const menu = [
  { id: 10, title: "All", image: all },
  { id: 11, title: "Snack", image: coffee },
  { id: 12, title: "Drink", image: juice },
  { id: 13, title: "Food", image: burger },
  { id: 14, title: "Dessert", image: dessert },
];
export const product = [
  // All
  {
    id: 1,
    category: "All",
    name: "Margherita Pizza",
    price: 8.99,
    image: "https://example.com/margherita-pizza.jpg",
    description: "Classic margherita pizza with fresh mozzarella and basil",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 2,
    category: "All",
    name: "Caesar Salad",
    price: 5.99,
    image: "https://example.com/caesar-salad.jpg",
    description: "Crisp romaine lettuce with Caesar dressing and croutons",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 3,
    category: "All",
    name: "Spaghetti Carbonara",
    price: 10.99,
    image: "https://example.com/spaghetti-carbonara.jpg",
    description: "Traditional Italian pasta with creamy sauce and pancetta",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 4,
    category: "All",
    name: "Chicken Alfredo",
    price: 12.99,
    image: "https://example.com/chicken-alfredo.jpg",
    description:
      "Fettuccine pasta with creamy Alfredo sauce and grilled chicken",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 5,
    category: "All",
    name: "Garlic Bread",
    price: 3.99,
    image: "https://example.com/garlic-bread.jpg",
    description: "Toasted bread with garlic butter and parsley",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 6,
    category: "All",
    name: "Tiramisu",
    price: 6.99,
    image: "https://example.com/tiramisu.jpg",
    description:
      "Classic Italian dessert with layers of mascarpone and coffee-soaked ladyfingers",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 7,
    category: "All",
    name: "Pepperoni Pizza",
    price: 9.99,
    image: "https://example.com/pepperoni-pizza.jpg",
    description: "Pepperoni pizza with mozzarella cheese and tomato sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 8,
    category: "All",
    name: "Minestrone Soup",
    price: 4.99,
    image: "https://example.com/minestrone-soup.jpg",
    description: "Hearty Italian soup with vegetables, beans, and pasta",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 9,
    category: "All",
    name: "Lasagna",
    price: 11.99,
    image: "https://example.com/lasagna.jpg",
    description: "Layers of pasta, meat sauce, and cheese baked to perfection",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 10,
    category: "All",
    name: "Caprese Salad",
    price: 7.99,
    image: "https://example.com/caprese-salad.jpg",
    description:
      "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },

  // Snack
  {
    id: 11,
    category: "Snack",
    name: "Nachos",
    price: 5.99,
    image: "https://example.com/nachos.jpg",
    description:
      "Crispy tortilla chips topped with melted cheese and jalapenos",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 12,
    category: "Snack",
    name: "Mozzarella Sticks",
    price: 6.99,
    image: "https://example.com/mozzarella-sticks.jpg",
    description:
      "Breaded and fried mozzarella sticks served with marinara sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 13,
    category: "Snack",
    name: "Spring Rolls",
    price: 4.99,
    image: "https://example.com/spring-rolls.jpg",
    description:
      "Crispy spring rolls filled with vegetables and served with dipping sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 14,
    category: "Snack",
    name: "Chicken Wings",
    price: 7.99,
    image: "https://example.com/chicken-wings.jpg",
    description: "Spicy chicken wings served with blue cheese dressing",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 15,
    category: "Snack",
    name: "Potato Skins",
    price: 6.49,
    image: "https://example.com/potato-skins.jpg",
    description: "Crispy potato skins topped with cheese and bacon",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 16,
    category: "Snack",
    name: "Stuffed Mushrooms",
    price: 5.99,
    image: "https://example.com/stuffed-mushrooms.jpg",
    description: "Mushrooms stuffed with cheese and herbs",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 17,
    category: "Snack",
    name: "Onion Rings",
    price: 4.99,
    image: "https://example.com/onion-rings.jpg",
    description: "Crispy fried onion rings served with dipping sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 18,
    category: "Snack",
    name: "Pretzel Bites",
    price: 5.49,
    image: "https://example.com/pretzel-bites.jpg",
    description: "Soft pretzel bites served with cheese sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 19,
    category: "Snack",
    name: "Cheese Platter",
    price: 8.99,
    image: "https://example.com/cheese-platter.jpg",
    description: "Assorted cheeses served with crackers and fruit",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 20,
    category: "Snack",
    name: "Hummus and Pita",
    price: 4.99,
    image: "https://example.com/hummus-pita.jpg",
    description: "Creamy hummus served with warm pita bread",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },

  // Drink
  {
    id: 21,
    category: "Drink",
    name: "Latte",
    price: 3.99,
    image: "https://example.com/latte.jpg",
    description: "Rich and creamy latte with steamed milk",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 22,
    category: "Drink",
    name: "Cappuccino",
    price: 3.49,
    image: "https://example.com/cappuccino.jpg",
    description: "Espresso with steamed milk and a thick layer of foam",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 23,
    category: "Drink",
    name: "Americano",
    price: 2.99,
    image: "https://example.com/americano.jpg",
    description: "Espresso with hot water",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 24,
    category: "Drink",
    name: "Espresso",
    price: 2.49,
    image: "https://example.com/espresso.jpg",
    description: "Strong and rich espresso",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 25,
    category: "Drink",
    name: "Iced Coffee",
    price: 3.99,
    image: "https://example.com/iced-coffee.jpg",
    description: "Cold brewed coffee served over ice",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 26,
    category: "Drink",
    name: "Green Tea",
    price: 2.99,
    image: "https://example.com/green-tea.jpg",
    description: "Refreshing green tea",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 27,
    category: "Drink",
    name: "Smoothie",
    price: 4.99,
    image: "https://example.com/smoothie.jpg",
    description: "Fresh fruit smoothie",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 28,
    category: "Drink",
    name: "Milkshake",
    price: 4.49,
    image: "https://example.com/milkshake.jpg",
    description: "Thick and creamy milkshake",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 29,
    category: "Drink",
    name: "Lemonade",
    price: 3.49,
    image: "https://example.com/lemonade.jpg",
    description: "Refreshing lemonade",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 30,
    category: "Drink",
    name: "Hot Chocolate",
    price: 3.99,
    image: "https://example.com/hot-chocolate.jpg",
    description: "Rich and creamy hot chocolate",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },

  // Food
  {
    id: 31,
    category: "Food",
    name: "Burger",
    price: 9.99,
    image: "https://example.com/burger.jpg",
    description: "Juicy beef burger with lettuce, tomato, and cheese",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 32,
    category: "Food",
    name: "Grilled Cheese Sandwich",
    price: 6.99,
    image: "https://example.com/grilled-cheese.jpg",
    description: "Toasted bread with melted cheese",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 33,
    category: "Food",
    name: "Chicken Tacos",
    price: 8.99,
    image: "https://example.com/chicken-tacos.jpg",
    description: "Soft tacos filled with grilled chicken and toppings",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 34,
    category: "Food",
    name: "Fish and Chips",
    price: 11.99,
    image: "https://example.com/fish-and-chips.jpg",
    description: "Crispy battered fish served with fries",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 35,
    category: "Food",
    name: "Steak",
    price: 15.99,
    image: "https://example.com/steak.jpg",
    description: "Grilled steak served with vegetables",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 36,
    category: "Food",
    name: "BBQ Ribs",
    price: 13.99,
    image: "https://example.com/bbq-ribs.jpg",
    description: "Tender ribs with BBQ sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 37,
    category: "Food",
    name: "Fried Chicken",
    price: 10.99,
    image: "https://example.com/fried-chicken.jpg",
    description: "Crispy fried chicken served with sides",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 38,
    category: "Food",
    name: "Vegetable Stir Fry",
    price: 9.49,
    image: "https://example.com/vegetable-stir-fry.jpg",
    description: "Stir-fried vegetables served with rice",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 39,
    category: "Food",
    name: "Pasta Primavera",
    price: 11.49,
    image: "https://example.com/pasta-primavera.jpg",
    description: "Pasta with fresh vegetables and a light sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 40,
    category: "Food",
    name: "Grilled Salmon",
    price: 14.99,
    image: "https://example.com/grilled-salmon.jpg",
    description: "Grilled salmon served with a side of vegetables",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },

  // Dessert
  {
    id: 41,
    category: "Dessert",
    name: "Chocolate Cake",
    price: 5.99,
    image: "https://example.com/chocolate-cake.jpg",
    description: "Rich and moist chocolate cake",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 42,
    category: "Dessert",
    name: "Cheesecake",
    price: 6.99,
    image: "https://example.com/cheesecake.jpg",
    description: "Creamy cheesecake with a graham cracker crust",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 43,
    category: "Dessert",
    name: "Apple Pie",
    price: 4.99,
    image: "https://example.com/apple-pie.jpg",
    description: "Classic apple pie with a flaky crust",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 44,
    category: "Dessert",
    name: "Brownies",
    price: 3.99,
    image: "https://example.com/brownies.jpg",
    description: "Fudgy chocolate brownies",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 45,
    category: "Dessert",
    name: "Ice Cream Sundae",
    price: 5.49,
    image: "https://example.com/ice-cream-sundae.jpg",
    description: "Ice cream sundae with toppings",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 46,
    category: "Dessert",
    name: "Panna Cotta",
    price: 6.49,
    image: "https://example.com/panna-cotta.jpg",
    description: "Creamy panna cotta with fruit sauce",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 47,
    category: "Dessert",
    name: "Creme Brulee",
    price: 6.99,
    image: "https://example.com/creme-brulee.jpg",
    description: "Rich custard with a caramelized sugar top",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 48,
    category: "Dessert",
    name: "Fruit Tart",
    price: 5.99,
    image: "https://example.com/fruit-tart.jpg",
    description: "Fresh fruit tart with a pastry crust",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 49,
    category: "Dessert",
    name: "Lemon Meringue Pie",
    price: 5.99,
    image: "https://example.com/lemon-meringue-pie.jpg",
    description: "Lemon pie with a meringue topping",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
  {
    id: 50,
    category: "Dessert",
    name: "Banana Split",
    price: 5.49,
    image: "https://example.com/banana-split.jpg",
    description: "Banana split with ice cream and toppings",
    quantity: 1,
    sizes: ["small", "medium", "large"],
  },
];
product.forEach((item) => {
  item.quantity = 20;
});
export const cashiers = [
  { username: 'cashier1', password: 'password1', name: 'Rak', role: 'Cashier' },
  { username: 'cashier2', password: 'password2', name: 'Nak', role: 'Cashier' },
  { username: 'cashier3', password: 'password3', name: 'Jefferson', role: 'Cashier' },
  { username: 'cashier4', password: 'password4', name: 'Enghav', role: 'Cashier' },
  { username: 'cashier5', password: 'password5', name: 'user', role: 'Cashier' },
];
